apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qty22rr7b-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qty22rr7b-dotnet-basic-gitops